# NumPy

## Завдання 1
 * Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
 * Виведіть вихідний масив.
 * Запитайте у користувача число (порогове значення).
 * Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
 * Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
 * Відсортуйте масив за спаданням і виведіть відсортований масив.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0, 50, size=20) 
arr

array([ 2, 40, 38, 15, 17, 16,  9, 21, 39, 42, 49, 42, 40, 35, 36, 47, 44,
        9, 45, 33], dtype=int32)

In [3]:
threshold = int(input("Введіть порогове значення: "))
count_greater = np.sum(arr > threshold)
print(f"Кількість елементів, більших за {threshold}: {count_greater}")

Введіть порогове значення:  56


Кількість елементів, більших за 56: 0


In [4]:
max_val = np.max(arr)
max_index = np.argmax(arr)
print(f"Максимальне значення: {max_val}, позиція першої появи: {max_index}")    

Максимальне значення: 49, позиція першої появи: 10


In [5]:
sorted_arr = np.sort(arr)[::-1]
print(f"Відсортований масив за спаданням: {sorted_arr}")

Відсортований масив за спаданням: [49 47 45 44 42 42 40 40 39 38 36 35 33 21 17 16 15  9  9  2]


## Завдання 2
 * Запитайте в користувача верхню та нижню межу діапазону чисел.
 * Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
 * Виведіть вихідну матрицю.
 * Отримайте головну діагональ і виведіть діагональні елементи.
 * Підрахуйте суму елементів головної діагоналі та виведіть результат.
 * Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [6]:
import numpy as np

In [7]:
low = int(input("Введіть нижню межу діапазону: "))
high = int(input("Введіть верхню межу діапазону: "))

Введіть нижню межу діапазону:  2
Введіть верхню межу діапазону:  7


In [8]:
if low >= high:
    print("Помилка: нижня межа має бути меншою за верхню.")
else:
        matrix = np.random.randint(low, high + 1, size=(5, 5))
        print("\nВихідна матриця:\n", matrix)

        diagonal_elements = []
        for i in range(5):
            diagonal_elements.append(matrix[i, i])
        
        print(f"\nЕлементи головної діагоналі: {diagonal_elements}")

        diag_sum = sum(diagonal_elements)
        print(f"Сума елементів головної діагоналі: {diag_sum}")

        for i in range(5):       
            for j in range(5):    
                if j > i:         
                    matrix[i, j] = 0

        print("\nМатриця після обнулення (вище діагоналі):\n", matrix)


Вихідна матриця:
 [[6 5 7 2 2]
 [2 2 5 6 3]
 [5 4 2 7 2]
 [4 6 2 7 3]
 [7 6 5 7 7]]

Елементи головної діагоналі: [np.int32(6), np.int32(2), np.int32(2), np.int32(7), np.int32(7)]
Сума елементів головної діагоналі: 24

Матриця після обнулення (вище діагоналі):
 [[6 0 0 0 0]
 [2 2 0 0 0]
 [5 4 2 0 0]
 [4 6 2 7 0]
 [7 6 5 7 7]]


## Завдання 3
 * Запитайте у користувача початок і кінець діапазону чисел.
 * Сформуйте послідовність цілих чисел у вказаному діапазоні.
 * Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
 * Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
 * Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [9]:
import numpy as np

In [10]:
begin = int(input("Введіть початок діапазону: "))
end = int(input("Введіть кінець діапазону: "))

Введіть початок діапазону:  3
Введіть кінець діапазону:  99


In [11]:
arr = np.random.randint(begin,end, size=(30))
arr

array([13, 37, 81, 89, 26, 47, 45, 43,  7, 46, 27,  9, 31, 55, 92, 93, 66,
        5, 70, 50, 40, 84, 82, 71, 39, 16, 72, 77, 93, 78], dtype=int32)

In [12]:
matrix = np.reshape(arr, shape=(6,5))
print("Матриця:\n",matrix)

Матриця:
 [[13 37 81 89 26]
 [47 45 43  7 46]
 [27  9 31 55 92]
 [93 66  5 70 50]
 [40 84 82 71 39]
 [16 72 77 93 78]]


In [13]:
row_sums = np.sum(matrix, axis=1)
print("Cума елементів кожного рядка:\n",row_sums)

Cума елементів кожного рядка:
 [246 188 214 284 316 336]


In [14]:
col_max = np.max(matrix, axis=0)
print("Максимальне значення у кожному стовпчику:\n",col_max)

Максимальне значення у кожному стовпчику:
 [93 84 82 93 92]


## Завдання 4
 * Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
 * Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
 * Виведіть вихідний масив.
 * Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
 * Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
 * Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.


In [20]:
low = int(input("Введіть нижню межу діапазону (можна від'ємне число): "))
high = int(input("Введіть верхню межу діапазону: "))

Введіть нижню межу діапазону (можна від'ємне число):  -50
Введіть верхню межу діапазону:  50


In [21]:
original = np.random.randint(low,high,size=(15))
original

array([-15, -18,  26,  22,  46,  -6, -24, -48, -46, -36, -10,   1,  14,
        -1, -16], dtype=int32)

In [23]:
negative_elements = original[original < 0]
print("Від'ємні елементи:\n",negative_elements)

Від'ємні елементи:
 [-15 -18  -6 -24 -48 -46 -36 -10  -1 -16]


In [25]:
modified_array = original.copy()
modified_array[modified_array < 0] = 0
print("Масив після заміни від'ємних чисел на 0:\n",modified_array)

Масив після заміни від'ємних чисел на 0:
 [ 0  0 26 22 46  0  0  0  0  0  0  1 14  0  0]


In [26]:
zeros_count = np.sum(modified_array == 0)
print("Кількість нульових елементів у зміненому масиві: ", zeros_count)

Кількість нульових елементів у зміненому масиві:  10
