# NumPy

## Завдання 1
* Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
* Виведіть вихідний масив.
* Запитайте у користувача число (порогове значення).
* Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
* Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
* Відсортуйте масив за спаданням і виведіть відсортований масив.

In [2]:
import numpy as np

In [6]:
arr = np.random.randint(0, 50, size=20) 
arr

array([ 6,  8, 40, 42, 42, 41,  9, 18, 17, 41, 43, 29, 49, 36, 36, 27, 29,
       30, 18, 12], dtype=int32)

In [7]:
threshold = int(input("Введіть порогове значення: "))
count_greater = np.sum(arr > threshold)
print(f"Кількість елементів, більших за {threshold}: {count_greater}")

Введіть порогове значення:  4


Кількість елементів, більших за 4: 20


In [9]:
max_val = np.max(arr)
max_index = np.argmax(arr)
print(f"Максимальне значення: {max_val}, позиція першої появи: {max_index}")    

Максимальне значення: 49, позиція першої появи: 12


In [11]:
sorted_arr = np.sort(arr)[::-1]
print(f"Відсортований масив за спаданням: {sorted_arr}")

Відсортований масив за спаданням: [49 43 42 42 41 41 40 36 36 30 29 29 27 18 18 17 12  9  8  6]


## Завдання 2
* Запитайте в користувача верхню та нижню межу діапазону чисел.
* Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
* Виведіть вихідну матрицю.
* Отримайте головну діагональ і виведіть діагональні елементи.
* Підрахуйте суму елементів головної діагоналі та виведіть результат.
* Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [12]:
import numpy as np

In [13]:
low = int(input("Введіть нижню межу діапазону: "))
high = int(input("Введіть верхню межу діапазону: "))

Введіть нижню межу діапазону:  5
Введіть верхню межу діапазону:  8


In [20]:
if low >= high:
    print("Помилка: нижня межа має бути меншою за верхню.")
else:
        matrix = np.random.randint(low, high + 1, size=(5, 5))
        print("\nВихідна матриця:\n", matrix)

        diagonal_elements = []
        for i in range(5):
            diagonal_elements.append(matrix[i, i])
        
        print(f"\nЕлементи головної діагоналі: {diagonal_elements}")

        diag_sum = sum(diagonal_elements)
        print(f"Сума елементів головної діагоналі: {diag_sum}")

        for i in range(5):       
            for j in range(5):    
                if j > i:         
                    matrix[i, j] = 0

        print("\nМатриця після обнулення (вище діагоналі):\n", matrix)


Вихідна матриця:
 [[8 7 5 8 7]
 [5 8 8 5 6]
 [6 5 7 7 5]
 [5 5 6 5 7]
 [8 5 7 5 7]]

Елементи головної діагоналі: [np.int32(8), np.int32(8), np.int32(7), np.int32(5), np.int32(7)]
Сума елементів головної діагоналі: 35

Матриця після обнулення (вище діагоналі):
 [[8 0 0 0 0]
 [5 8 0 0 0]
 [6 5 7 0 0]
 [5 5 6 5 0]
 [8 5 7 5 7]]
