# NumPy

## Завдання 1
 * Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
 * Виведіть вихідний масив.
 * Запитайте у користувача число (порогове значення).
 * Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
 * Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
 * Відсортуйте масив за спаданням і виведіть відсортований масив.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0, 50, size=20) 
arr

array([13,  0,  1, 11, 29, 34, 45, 45, 43, 19, 27, 48, 15, 22, 22, 36, 20,
       30, 30,  2], dtype=int32)

In [3]:
threshold = int(input("Введіть порогове значення: "))
count_greater = np.sum(arr > threshold)
print(f"Кількість елементів, більших за {threshold}: {count_greater}")

Введіть порогове значення:  56


Кількість елементів, більших за 56: 0


In [4]:
max_val = np.max(arr)
max_index = np.argmax(arr)
print(f"Максимальне значення: {max_val}, позиція першої появи: {max_index}")    

Максимальне значення: 48, позиція першої появи: 11


In [5]:
sorted_arr = np.sort(arr)[::-1]
print(f"Відсортований масив за спаданням: {sorted_arr}")

Відсортований масив за спаданням: [48 45 45 43 36 34 30 30 29 27 22 22 20 19 15 13 11  2  1  0]


## Завдання 2
 * Запитайте в користувача верхню та нижню межу діапазону чисел.
 * Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
 * Виведіть вихідну матрицю.
 * Отримайте головну діагональ і виведіть діагональні елементи.
 * Підрахуйте суму елементів головної діагоналі та виведіть результат.
 * Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [6]:
import numpy as np

In [7]:
low = int(input("Введіть нижню межу діапазону: "))
high = int(input("Введіть верхню межу діапазону: "))

Введіть нижню межу діапазону:  2
Введіть верхню межу діапазону:  7


In [8]:
if low >= high:
    print("Помилка: нижня межа має бути меншою за верхню.")
else:
        matrix = np.random.randint(low, high + 1, size=(5, 5))
        print("\nВихідна матриця:\n", matrix)

        diagonal_elements = []
        for i in range(5):
            diagonal_elements.append(matrix[i, i])
        
        print(f"\nЕлементи головної діагоналі: {diagonal_elements}")

        diag_sum = sum(diagonal_elements)
        print(f"Сума елементів головної діагоналі: {diag_sum}")

        for i in range(5):       
            for j in range(5):    
                if j > i:         
                    matrix[i, j] = 0

        print("\nМатриця після обнулення (вище діагоналі):\n", matrix)


Вихідна матриця:
 [[3 2 2 2 4]
 [7 5 5 5 4]
 [5 3 6 5 5]
 [5 4 3 7 4]
 [3 6 5 2 2]]

Елементи головної діагоналі: [np.int32(3), np.int32(5), np.int32(6), np.int32(7), np.int32(2)]
Сума елементів головної діагоналі: 23

Матриця після обнулення (вище діагоналі):
 [[3 0 0 0 0]
 [7 5 0 0 0]
 [5 3 6 0 0]
 [5 4 3 7 0]
 [3 6 5 2 2]]


## Завдання 3
 * Запитайте у користувача початок і кінець діапазону чисел.
 * Сформуйте послідовність цілих чисел у вказаному діапазоні.
 * Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
 * Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
 * Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [9]:
import numpy as np

In [10]:
begin = int(input("Введіть початок діапазону: "))
end = int(input("Введіть кінець діапазону: "))

Введіть початок діапазону:  3
Введіть кінець діапазону:  7


In [11]:
arr = np.random.randint(begin,end, size=(30))
arr

array([5, 5, 4, 3, 4, 6, 5, 4, 6, 4, 6, 5, 5, 3, 3, 4, 4, 3, 3, 6, 5, 5,
       4, 4, 4, 3, 5, 6, 3, 6], dtype=int32)

In [12]:
matrix = np.reshape(arr, shape=(6,5))
print("Матриця:\n",matrix)

Матриця:
 [[5 5 4 3 4]
 [6 5 4 6 4]
 [6 5 5 3 3]
 [4 4 3 3 6]
 [5 5 4 4 4]
 [3 5 6 3 6]]


In [13]:
row_sums = np.sum(matrix, axis=1)
print("Cума елементів кожного рядка:\n",row_sums)

Cума елементів кожного рядка:
 [21 25 22 20 22 23]


In [14]:
col_max = np.max(matrix, axis=0)
print("Максимальне значення у кожному стовпчику:\n",col_max)

Максимальне значення у кожному стовпчику:
 [6 5 6 6 6]


## Завдання 4
 * Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
 * Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
 * Виведіть вихідний масив.
 * Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
 * Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
 * Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.


In [15]:
low = int(input("Введіть нижню межу діапазону (можна від'ємне число): "))
high = int(input("Введіть верхню межу діапазону: "))

Введіть нижню межу діапазону (можна від'ємне число):  28
Введіть верхню межу діапазону:  367


In [16]:
original = np.random.randint(low,high,size=(15))
original

array([235, 190,  42, 251, 106, 131, 181, 169,  56, 146, 131,  89, 342,
       203, 275], dtype=int32)

In [17]:
negative_elements = original[original < 0]
print("Від'ємні елементи:\n",negative_elements)

Від'ємні елементи:
 []


In [18]:
modified_array = original.copy()
modified_array[modified_array < 0] = 0
print("Масив після заміни від'ємних чисел на 0:\n",modified_array)

Масив після заміни від'ємних чисел на 0:
 [235 190  42 251 106 131 181 169  56 146 131  89 342 203 275]


In [19]:
zeros_count = np.sum(modified_array == 0)
print("Кількість нульових елементів у зміненому масиві: ", zeros_count)

Кількість нульових елементів у зміненому масиві:  0


## Завдання 5

 * Запитайте в користувача довжину масивів.
 * Створіть два одновимірні масиви вказаної довжини:
   - перший заповніть випадковими числами від 0 до 10;
   - другий заповніть випадковими числами від 10 до 20.
 * Виведіть обидва вихідні масиви.
 * Об'єднайте масиви в один і виведіть результат.
 * Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.

In [27]:
n = int(input("Введіть довжину масивів: "))

Введіть довжину масивів:  10


In [28]:
arr_a = np.random.randint(0,20,size=(n))
print("Масив А:\n", arr_a)
arr_b = np.random.randint(10,20,size=(n))
print("Масив B:\n", arr_b)

Масив А:
 [ 4 15 12 17 13  9 10  9  1  8]
Масив B:
 [12 13 17 11 19 12 13 11 16 12]


In [29]:
concatenated_arr = np.concatenate((arr_a, arr_b))
print("Об'єднанний масив:\n", concatenated_arr)

Об'єднанний масив:
 [ 4 15 12 17 13  9 10  9  1  8 12 13 17 11 19 12 13 11 16 12]


In [30]:
sum_arr = arr_a + arr_b
diff_arr = arr_a - arr_b

print("Результат додавання:\n", sum_arr)
print("Результат різниці:\n", diff_arr)

Результат додавання:
 [16 28 29 28 32 21 23 20 17 20]
Результат різниці:
 [ -8   2  -5   6  -6  -3  -3  -2 -15  -4]


## Завдання 6
 * Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
 * Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
 * Виведіть вихідну матрицю.
 * Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
 * Виведіть отриману матрицю.
 * Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
 * Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [31]:
rows = int(input("Введіть довжину рядків: "))
cols = int(input("Введіть довжину стовбців: "))

Введіть довжину рядків:  4
Введіть довжину стовбців:  6


In [32]:
matrix = np.arange(rows * cols).reshape(rows, cols)
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
new_rows = int(input("Введіть нову довжину рядків: "))
new_cols = int(input("Введіть нову довжину стовбців: "))

Введіть нову довжину рядків:  2
Введіть нову довжину стовбців:  12


In [35]:
resh = np.reshape(matrix, shape=(new_rows,new_cols))
print("Зміненна матриця за формою:\n",resh)

Зміненна матриця за формою:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [39]:
row_min = np.min(resh, axis=1)
row_max = np.max(resh, axis=1)
print("Мінімальні значення в кожному рядку:", row_min)
print("Максимальні значення в кожному рядку:", row_max)

Мінімальні значення в кожному рядку: [ 0 12]
Максимальні значення в кожному рядку: [11 23]


In [38]:
total_sum = np.sum(resh)
print("Загальна сума всіх елементів матриці:", total_sum)

Загальна сума всіх елементів матриці: 276
