# NumPy

## Завдання 1
* Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(0, 100, size=10)
rand10

array([ 9, 21, 31, 38, 31, 25, 14, 91, 52, 28], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 9, максимальне 91 та середнє значення масиву 34.000000


In [5]:
print(rand10, np.sort(rand10), sep='\n')

[ 9 21 31 38 31 25 14 91 52 28]
[ 9 14 21 25 28 31 31 38 52 91]


## Завдання 2
* Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
rand_4_4 = np.random.randint(1, 20, size=(4,4))
rand_4_4

array([[ 9, 10, 12,  4],
       [ 1, 19, 16, 16],
       [11,  9, 19, 14],
       [ 1,  4, 18, 18]], dtype=int32)

In [7]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[22 42 65 52] [35 52 53 41] 11.3125


In [8]:
print(*["%s | %d" % (k,v) for (k,v) in 
        zip(rand_4_4, np.sum(rand_4_4, axis=1))], 
      "-----------------",
      np.sum(rand_4_4, axis=0), sep='\n', end=' | ')
print(np.mean(rand_4_4))

[ 9 10 12  4] | 35
[ 1 19 16 16] | 52
[11  9 19 14] | 53
[ 1  4 18 18] | 41
-----------------
[22 42 65 52] | 11.3125


## Завдання 3
* Створіть масив розміром 3×5, заповнений числами від 0 до 14.
* Виведіть вихідний масив.
* Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
* Застосуйте операцію reshape, щоб отримати масив 5×3.
* Відобразіть результати на екран.

In [9]:
rand_3_5 = np.random.randint(0, 14, size=(3,5))
rand_3_5

array([[ 2,  8, 10, 11,  8],
       [ 4,  2,  7,  4,  3],
       [10,  5,  2, 13, 13]], dtype=int32)

In [10]:
print("Форма масиву: ", rand_3_5.shape)

Форма масиву:  (3, 5)


In [11]:
trans = np.transpose(rand_3_5)
print("Транспонування:\n", trans)
print("Форма транспонованого масиву: ", trans.shape)

Транспонування:
 [[ 2  4 10]
 [ 8  2  5]
 [10  7  2]
 [11  4 13]
 [ 8  3 13]]
Форма транспонованого масиву:  (5, 3)


In [12]:
resh = np.reshape(rand_3_5, shape=(5,3))
print("Зміна розмірності (решейпінг):\n", resh)
print("Форма нового масиву: ", resh.shape)
# дія решейпінгу - серіалізація вихідного масиву 
# (перенесення в один вимір один-за-одним)
# та наступний переділ згідно з заданими
# розмірностями 

Зміна розмірності (решейпінг):
 [[ 2  8 10]
 [11  8  4]
 [ 2  7  4]
 [ 3 10  5]
 [ 2 13 13]]
Форма нового масиву:  (5, 3)


## Завдання 4
* Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
* Знайдіть мінімальне та максимальне значення в усьому масиві.
* Визначте індекси мінімального та максимального елементів
(наприклад: (рядок, стовпець)).
* Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [13]:
rand_10_10 = np.random.rand(10,10)  # виведення великих об'ємів незручне
np.set_printoptions(precision=4)    # Тільки для виведення можна обмежити
print(*rand_10_10, sep='\n')        # точність (тільки для масивів)

[0.4419 0.2059 0.8957 0.8014 0.8313 0.876  0.201  0.7296 0.4302 0.0898]
[0.8075 0.3358 0.5142 0.3991 0.9544 0.5668 0.8575 0.0753 0.795  0.5957]
[0.5015 0.39   0.0871 0.297  0.8008 0.0778 0.6929 0.8284 0.2917 0.324 ]
[0.623  0.969  0.9926 0.8149 0.4822 0.3386 0.6738 0.8567 0.5142 0.3246]
[0.0357 0.6541 0.8972 0.3454 0.436  0.1167 0.2228 0.1379 0.2935 0.9269]
[0.4228 0.586  0.6493 0.0192 0.9975 0.2736 0.1749 0.9498 0.6957 0.9642]
[0.1138 0.4854 0.6613 0.3953 0.8052 0.5703 0.6903 0.2926 0.0258 0.1804]
[0.7907 0.2781 0.7743 0.2739 0.1073 0.5415 0.5421 0.5005 0.6012 0.9738]
[0.4085 0.6331 0.2875 0.0705 0.4151 0.4942 0.1157 0.4477 0.5534 0.9267]
[0.5276 0.8833 0.4745 0.7336 0.856  0.3132 0.1251 0.5325 0.6927 0.311 ]


In [14]:
max_v = np.max(rand_10_10)
print("Максимальне значення у масиві: ", max_v)
max_i = np.argmax(rand_10_10)  # індекс суцільний - від самого початку масиву
print("Знаходиться за індексом: ", max_i)
# перераховуємо суцільний індекс на набір індексів по заданій формі масиву
max_coord = np.unravel_index(max_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, max_coord)))


Максимальне значення у масиві:  0.997506087815656
Знаходиться за індексом:  54
Що відповідає сукупності індексів: 5, 4


In [15]:
min_v = np.min(rand_10_10)
print("Максимальне значення у масиві: ", min_v)
min_i = np.argmin(rand_10_10) 
print("Знаходиться за індексом: ", min_i)
min_coord = np.unravel_index(min_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, min_coord)))

Максимальне значення у масиві:  0.01916353575090224
Знаходиться за індексом:  53
Що відповідає сукупності індексів: 5, 3


## Завдання 

Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.

 * Виведіть масив.
 * За допомогою булевої індексації виберіть тільки додатні елементи.
 * За допомогою булевої індексації виберіть тільки парні елементи.
 * Виведіть обидва результати на екран.

In [16]:
rand_15 = np.random.randint(-19,10,size=15)
print(rand_15)

[-15   3 -15   5   7 -11  -2  -9   9  -4 -12 -18 -17  -8  -3]


In [18]:
res_pos = rand_15 > 0
print("Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:\n", 
      res_pos)
print("Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:\n", 
      rand_15[res_pos])
print("Кількість додатнії елементів:", np.count_nonzero(res_pos))

Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:
 [False  True False  True  True False False False  True False False False
 False False False]
Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:
 [3 5 7 9]
Кількість додатнії елементів: 4


In [19]:
print("Парні значення:", rand_15[rand_15 % 2 == 0])

Парні значення: [ -2  -4 -12 -18  -8]
