# NumPy

## Завдання 1
 * Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
 * Збережіть масив у змінну і виведіть його на екран.
 * Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
 * Відсортуйте масив за зростанням і виведіть результат.
 * Відобразіть масив до і після сортування.

In [1]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
rand10 = np.random.randint(0, 100, size=10)
rand10

array([23, 17, 93, 40, 32, 76, 24, 52, 20, 55], dtype=int32)

In [5]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 17, максимальне 93 та середнє значення масиву 43.200000


In [6]:
print(rand10, np.sort(rand10), sep='\n')

[23 17 93 40 32 76 24 52 20 55]
[17 20 23 24 32 40 52 55 76 93]


## Завдання 2
 * Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
 * Виведіть масив у читабельному вигляді (у вигляді таблиці).
 * Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
 * Визначте загальне середнє значення масиву.
 * Виведіть усі результати в зручному вигляді (наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [7]:
rand_4_4 = np.random.randint(1, 20, size=(4,4))
rand_4_4

array([[ 6,  9, 13,  3],
       [17, 17,  7,  3],
       [ 6, 17, 19,  3],
       [19,  1,  5, 11]], dtype=int32)

In [8]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[48 44 44 20] [31 44 45 36] 9.75


In [9]:
print(*["%s | %d" % (k,v) for (k,v) in 
        zip(rand_4_4, np.sum(rand_4_4, axis=1))], 
      "-----------------",
      np.sum(rand_4_4, axis=0), sep='\n', end=' | ')
print(np.mean(rand_4_4))

[ 6  9 13  3] | 31
[17 17  7  3] | 44
[ 6 17 19  3] | 45
[19  1  5 11] | 36
-----------------
[48 44 44 20] | 9.75
