# NumPy

## Завдання 1
* Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(0, 100, size=10)
rand10

array([67, 10, 63, 40, 96, 82, 64,  2,  3, 68], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))

мінімальне: 2, максимальне 96 та середнє значення масиву 49.500000


In [5]:
print(rand10, np.sort(rand10), sep='\n')

[67 10 63 40 96 82 64  2  3 68]
[ 2  3 10 40 63 64 67 68 82 96]


## Завдання 2
* Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [6]:
rand_4_4 = np.random.randint(1, 20, size=(4,4))
rand_4_4

array([[17, 18, 15,  1],
       [19, 12,  5, 17],
       [ 4, 17, 15, 17],
       [ 1,  8, 13,  5]], dtype=int32)

In [7]:
print(np.sum(rand_4_4, axis=0),  # columns
      np.sum(rand_4_4, axis=1),  # rows
      np.mean(rand_4_4))

[41 55 48 40] [51 53 53 27] 11.5


In [8]:
print(*["%s | %d" % (k,v) for (k,v) in 
        zip(rand_4_4, np.sum(rand_4_4, axis=1))], 
      "-----------------",
      np.sum(rand_4_4, axis=0), sep='\n', end=' | ')
print(np.mean(rand_4_4))

[17 18 15  1] | 51
[19 12  5 17] | 53
[ 4 17 15 17] | 53
[ 1  8 13  5] | 27
-----------------
[41 55 48 40] | 11.5


## Завдання 3
* Створіть масив розміром 3×5, заповнений числами від 0 до 14.
* Виведіть вихідний масив.
* Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
* Застосуйте операцію reshape, щоб отримати масив 5×3.
* Відобразіть результати на екран.

In [9]:
rand_3_5 = np.random.randint(0, 14, size=(3,5))
rand_3_5

array([[ 1, 11, 10,  1,  1],
       [ 0,  2, 10,  2, 13],
       [ 3, 12, 11, 13, 13]], dtype=int32)

In [10]:
print("Форма масиву: ", rand_3_5.shape)

Форма масиву:  (3, 5)


In [11]:
trans = np.transpose(rand_3_5)
print("Транспонування:\n", trans)
print("Форма транспонованого масиву: ", trans.shape)

Транспонування:
 [[ 1  0  3]
 [11  2 12]
 [10 10 11]
 [ 1  2 13]
 [ 1 13 13]]
Форма транспонованого масиву:  (5, 3)


In [12]:
resh = np.reshape(rand_3_5, shape=(5,3))
print("Зміна розмірності (решейпінг):\n", resh)
print("Форма нового масиву: ", resh.shape)
# дія решейпінгу - серіалізація вихідного масиву 
# (перенесення в один вимір один-за-одним)
# та наступний переділ згідно з заданими
# розмірностями 

Зміна розмірності (решейпінг):
 [[ 1 11 10]
 [ 1  1  0]
 [ 2 10  2]
 [13  3 12]
 [11 13 13]]
Форма нового масиву:  (5, 3)


## Завдання 4
* Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
* Знайдіть мінімальне та максимальне значення в усьому масиві.
* Визначте індекси мінімального та максимального елементів
(наприклад: (рядок, стовпець)).
* Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [13]:
rand_10_10 = np.random.rand(10,10)  # виведення великих об'ємів незручне
np.set_printoptions(precision=4)    # Тільки для виведення можна обмежити
print(*rand_10_10, sep='\n')        # точність (тільки для масивів)

[0.7119 0.4222 0.2179 0.3345 0.0318 0.5672 0.6138 0.2794 0.5027 0.6225]
[0.3428 0.2625 0.0407 0.0905 0.1897 0.2151 0.0151 0.4649 0.2919 0.4163]
[0.8139 0.0647 0.1366 0.1974 0.826  0.1559 0.1351 0.9992 0.6904 0.7043]
[0.5213 0.3735 0.6846 0.3223 0.2558 0.3232 0.2186 0.6158 0.7174 0.2413]
[0.9027 0.3701 0.4414 0.6621 0.2001 0.1037 0.8312 0.4501 0.6456 0.9036]
[0.7316 0.7474 0.4762 0.2346 0.3409 0.3695 0.7733 0.9337 0.389  0.586 ]
[0.3937 0.0695 0.1668 0.7538 0.7974 0.507  0.2598 0.0925 0.501  0.1913]
[0.2382 0.7914 0.1005 0.8565 0.7609 0.298  0.6904 0.3212 0.7782 0.2586]
[0.491  0.0073 0.4453 0.9635 0.6145 0.5944 0.3422 0.2287 0.2648 0.8069]
[0.2829 0.0182 0.7014 0.0331 0.6513 0.2624 0.3674 0.4831 0.987  0.5256]


In [14]:
max_v = np.max(rand_10_10)
print("Максимальне значення у масиві: ", max_v)
max_i = np.argmax(rand_10_10)  # індекс суцільний - від самого початку масиву
print("Знаходиться за індексом: ", max_i)
# перераховуємо суцільний індекс на набір індексів по заданій формі масиву
max_coord = np.unravel_index(max_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, max_coord)))


Максимальне значення у масиві:  0.9992179904527491
Знаходиться за індексом:  27
Що відповідає сукупності індексів: 2, 7


In [15]:
min_v = np.min(rand_10_10)
print("Максимальне значення у масиві: ", min_v)
min_i = np.argmin(rand_10_10) 
print("Знаходиться за індексом: ", min_i)
min_coord = np.unravel_index(min_i, rand_10_10.shape)
print("Що відповідає сукупності індексів:", ", ".join(map(str, min_coord)))

Максимальне значення у масиві:  0.007331424998665459
Знаходиться за індексом:  81
Що відповідає сукупності індексів: 8, 1


## Завдання 5

Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.

 * Виведіть масив.
 * За допомогою булевої індексації виберіть тільки додатні елементи.
 * За допомогою булевої індексації виберіть тільки парні елементи.
 * Виведіть обидва результати на екран.

In [16]:
rand_15 = np.random.randint(-19,10,size=15)
print(rand_15)

[  3 -16  -2 -18  -5   7  -9   2  -2   7  -5   2 -19   8 -14]


In [17]:
res_pos = rand_15 > 0
print("Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:\n", 
      res_pos)
print("Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:\n", 
      rand_15[res_pos])
print("Кількість додатнії елементів:", np.count_nonzero(res_pos))

Булева індексація дозволяє застосувати умову до масиву і одержати масив результатів:
 [ True False False False False  True False  True False  True False  True
 False  True False]
Використання масиву булевих значень як індексу залишає лише ті елементи, для яких True:
 [3 7 2 7 2 8]
Кількість додатнії елементів: 6


In [18]:
print("Парні значення:", rand_15[rand_15 % 2 == 0])

Парні значення: [-16  -2 -18   2  -2   2   8 -14]


## Завдання 6
* Створіть два одновимірні масиви довжиною 5: перший заповніть числами від 1 до 5, другий — числами від 6 до 10.
* Об'єднайте їх в один масив за допомогою np.concatenate.
* Побудуйте двовимірний масив 2×5, у якому перший рядок — перший масив, а другий рядок — другий масив.
* Об'єднайте обидва масиви в одну колонку (розмірність 5×2).
* Виведіть усі три результати на екран.

In [24]:
rand1 = np.random.randint(1,5,size=5)
rand2 = np.random.randint(6,10,size=5)
print(rand1, rand2,
        np.concatenate((rand1, rand2)),
        np.array((rand1, rand2)),
        np.transpose(np.array((rand1,rand2))),
        sep='\n')

[1 1 2 1 2]
[8 7 8 8 7]
[1 1 2 1 2 8 7 8 8 7]
[[1 1 2 1 2]
 [8 7 8 8 7]]
[[1 8]
 [1 7]
 [2 8]
 [1 8]
 [2 7]]
